### PR TITLE
Html message

### PR DESCRIPTION
**Pull request by OndraM**
Sometimes HTML in message content could be useful, e.g. when using something like `<strong>` for message header, `<a>` for links in message etc.

This PR adds support to disable escaping, using new ngBindHtml (thus creating dependency on angular 1.2). The configuration is similar as for TTL - either global or on per-message basis.

### CODE REVIEW

**Comment by marcorinck** [comment]
Thats a nice idea, I like it!

However, I have 2 issues with it: 
- I don't want to release angular-growl with a hard dependency to angularJS 1.2 just yet. animations just don't work without any error if used with angular < 1.2.  If you don't want to change it, I'll merge it only when angularJS 1.2 is released as stable
- the only reason to disable escaping would be to support html messages, right? If so, I would like to rename "disableEscaping" to "enableHtml"

What do you think?

**Comment by OndraM** [comment]
I've renamed the property to enableHtml, that makes sense.

About the angular 1.2 dependency - it is not possible to write compatible code for both 1.0 and 1.2, as the directive name and also ngSanitize dependency has changed. So if you don't want to make dependency on rc2 version, than yes, it is ok to wait to 1.2 stable :).

**Comment by bchatelard** [comment]
:+1:

**Comment by gustafnk** [comment]
:+1:

**Comment by OndraM** [comment]
Hi, angular 1.2.0 was released over a week ago, and even 1.2.1 is out now. Any plans merging this PR and releasing new angular-growl version?

**Comment by tschiela** [comment]
+1
need that feature

**Comment by marcorinck** [comment]
Sorry for the delay, had a lot to do in the last weeks. I think an update will be ready this week. So stay tuned!

**Comment by marcorinck** [comment]
merged this just now and released v0.4.0

**Pull request merged**
